import { TodoCreateInputObjectZodSchema, TodoSchema } from "@repo/db/schema";
import { z } from "zod";
import { type NullToUndefinedType, withNullAsUndefined, withUndefinedAsNull } from "./lib/zod-helpers.js";

/**
 * Field-specific validation extensions
 * These extend the Prisma-generated base schemas with additional validation rules
 */
const fields = z.object({
  title: z
    .string()
    .min(3, "Title must be at least 3 characters")
    .max(100, "Title must be at most 100 characters")
    .regex(/^[a-z0-9 _-]+$/i, "Only letters, numbers, spaces, _ and - are allowed"),
  description: z.string().max(500, "Description must be at most 500 characters").optional(),
});

/**
 * Input schema for creating a new todo
 * Uses Prisma-generated schema as base, omits auto-generated fields,
 * and extends with enhanced validation for specific fields.
 * Automatically transforms undefined → null for Prisma compatibility.
 */
export const createTodoInputSchema = withUndefinedAsNull(
  TodoCreateInputObjectZodSchema.omit({
    createdAt: true, // Auto-generated by database
  }).extend(fields.shape),
);

/**
 * Input schema for updating a todo (PUT - full replacement)
 * Uses the same validation as create, ensuring all fields are provided
 */
export const updateTodoInputSchema = createTodoInputSchema;

/**
 * Output schema for a single todo
 * Automatically transforms null → undefined for TypeScript/UI conventions
 */
export const todoOutputSchema = withNullAsUndefined(TodoSchema);

/**
 * Param schema for todo ID in route parameters
 */
export const todoIdParamSchema = z.object({
  id: z.coerce.number().int().positive(),
});

/**
 * Type exports for convenience
 */
export type CreateTodoInput = z.infer<typeof createTodoInputSchema>;
export type UpdateTodoInput = z.infer<typeof updateTodoInputSchema>;

/**
 * Output type with null transformed to undefined
 * Uses NullToUndefinedType helper to automatically transform all nullable fields
 */
export type TodoOutput = NullToUndefinedType<z.infer<typeof TodoSchema>>;

export type TodoIdParam = z.infer<typeof todoIdParamSchema>;
